question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "Rabbits can&#039;t vomit.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "Which of these bones is hardest to break?",
        "correct_answer": "Femur",
        "incorrect_answers": ["Cranium", "Humerus", "Tibia"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "For the film &quot;Raiders of The Lost Ark&quot;, what was Harrison Ford sick with during the filming of the Cairo chase?",
        "correct_answer": "Dysentery",
        "incorrect_answers": ["Anemia", "Constipation", "Acid Reflux "],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Rocket League is a game which features..",
        "correct_answer": "Cars",
        "incorrect_answers": ["Helicopters", "Planes", "Submarines"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "New Haven is the capital city of the state of Connecticut in the United States.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Geography",
        "question": "In which Indian city can the Taj Mahal be found?",
        "correct_answer": "Agra",
        "incorrect_answers": ["Mumbai", "Faridabad", "Thane"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "The United States was a member of the League of Nations.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "What is the name of the largest planet in Kerbal Space Program?",
        "correct_answer": "Jool",
        "incorrect_answers": ["Eeloo", "Kerbol", "Minmus"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Which of these Marvel games was released on the Playstation 2?",
        "correct_answer": "Spider-Man 2",
        "incorrect_answers": [
            "Silver Surfer",
            "Howard the Duck",
            "Wolverine: Adamantium Rage",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Vehicles",
        "question": "The Italian automaker Lamborghini uses what animal as its logo?",
        "correct_answer": "Bull",
        "incorrect_answers": ["Bat", "Horse", "Snake"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "Stars consist mainly of hydrogen and which other gas?",
        "correct_answer": "Helium",
        "incorrect_answers": ["Oxygen", "Argon", "Nitrogen"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "What year did the game &quot;Overwatch&quot; enter closed beta?",
        "correct_answer": "2015",
        "incorrect_answers": ["2013", "2011", "2016"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "What nuts are used in the production of marzipan?",
        "correct_answer": "Almonds",
        "incorrect_answers": ["Peanuts", "Walnuts", "Pistachios"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Geography",
        "question": "What colour is the circle on the Japanese flag?",
        "correct_answer": "Red",
        "incorrect_answers": ["White", "Yellow", "Black"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Politics",
        "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In most FPS video games such as Counter-Strike, shooting which part of the body does the highest damage?",
        "correct_answer": "Head",
        "incorrect_answers": ["Arm", "Leg", "Chest"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "What is the largest animal currently on Earth?",
        "correct_answer": "Blue Whale",
        "incorrect_answers": ["Orca", "Colossal Squid", "Giraffe"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Who is the last boss in Night In The Woods&#039; Demontower minigame?",
        "correct_answer": "The Blood Thief",
        "incorrect_answers": ["Mega Hairball ", "King Skellie ", "Krampus "],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Sports",
        "question": "What is the name of Manchester United&#039;s home stadium?",
        "correct_answer": "Old Trafford",
        "incorrect_answers": ["Anfield", "City of Manchester Stadium", "St James Park"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Books",
        "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "History",
        "question": "Who rode on horseback to warn the Minutemen that the British were coming during the U.S. Revolutionary War?",
        "correct_answer": "Paul Revere",
        "incorrect_answers": ["Thomas Paine", "Henry Longfellow", "Nathan Hale"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "Cats have whiskers under their legs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Which of these holidays is NOT usually celebrated in the month of December?",
        "correct_answer": "Thanksgiving",
        "incorrect_answers": ["Christmas", "Kwanzaa", "Hanukkah"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Music",
        "question": "Which Beatles album does NOT feature any of the band members on it&#039;s cover?",
        "correct_answer": "The Beatles (White Album)",
        "incorrect_answers": ["Rubber Soul", "Abbey Road", "Magical Mystery Tour"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Who starred in the film 1973 movie &quot;Enter The Dragon&quot;?",
        "correct_answer": "Bruce Lee",
        "incorrect_answers": ["Jackie Chan", "Jet Li", " Yun-Fat Chow"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "This movie contains the quote, &quot;Houston, we have a problem.&quot;",
        "correct_answer": "Apollo 13",
        "incorrect_answers": ["The Right Stuff", "Capricorn One", "Marooned"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Sports",
        "question": "How many soccer players should be on the field at the same time?",
        "correct_answer": "22",
        "incorrect_answers": ["20", "24", "26"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "History",
        "question": "Which of these countries remained neutral during World War II?",
        "correct_answer": "Switzerland",
        "incorrect_answers": ["United Kingdom", "France", "Italy"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Which of the following card games revolves around numbers and basic math?",
        "correct_answer": "Uno",
        "incorrect_answers": ["Go Fish", "Twister", "Munchkin"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Music",
        "question": "The K-Pop Boy Band BTS debuted in the year 2013.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Politics",
        "question": "Which former US president was nicknamed &quot;Teddy&quot; after he refused to shoot a defenseless black bear?",
        "correct_answer": "Theodore Roosevelt",
        "incorrect_answers": ["Woodrow Wilson", "James F. Fielder", "Andrew Jackson"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Sports",
        "question": "Which two teams played in Super Bowl XLII?",
        "correct_answer": "The New York Giants &amp; The New England Patriots",
        "incorrect_answers": [
            "The Green Bay Packers &amp; The Pittsburgh Steelers",
            "The Philadelphia Eagles &amp; The New England Patriots",
            "The Seattle Seahawks &amp; The Denver Broncos",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Rust, how many Timed Explosive Charges does it take to destroy a Ladder Hatch?",
        "correct_answer": "1",
        "incorrect_answers": ["3", "2", "5"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Which programming language shares its name with an island in Indonesia?",
        "correct_answer": "Java",
        "incorrect_answers": ["Python", "C", "Jakarta"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Which water-type Pok&eacute;mon starter was introduced in the 4th generation of the series?",
        "correct_answer": "Piplup",
        "incorrect_answers": ["Totodile", "Oshawott", "Mudkip"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?",
        "correct_answer": "Cabbage Patch Kids",
        "incorrect_answers": ["Transformers", "Care Bears", "Rubik&rsquo;s Cube"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Which of these African regions does *not* directly border the Democratic Republic of The Congo?",
        "correct_answer": "Sudan",
        "incorrect_answers": ["Central African Republic", "Tanzania", "Zambia"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Board Games",
        "question": "Which of these board games do NOT utilize standard 6-sided dice?",
        "correct_answer": "The Game of Life",
        "incorrect_answers": ["Monopoly", "Risk", "Snakes and Ladders"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "What is the name of the company in Lethal Company?",
        "correct_answer": "The Company",
        "incorrect_answers": [
            "Planet Scrap Co.",
            "Lethal Robotics",
            "Gordian Shipping Co.",
        ],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Which computer language would you associate Django framework with?",
        "correct_answer": "Python",
        "incorrect_answers": ["C#", "C++", "Java"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Vehicles",
        "question": "Which of the following vehicles from Ford is named after a WW2 Fighter Plane?",
        "correct_answer": "Mustang",
        "incorrect_answers": ["Explorer", "Ranger", "Galaxy"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Art",
        "question": "Which artist painted the late 15th century mural &#039;The Last Supper&#039;?",
        "correct_answer": "Leonardo da Vinci",
        "incorrect_answers": ["Piero della Francesca", "Paolo Uccello", "Luca Pacioli"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Television",
        "question": "Who was the first ever actor to play &quot;The Doctor&quot; on &quot;Doctor Who&quot;?",
        "correct_answer": "William Hartnell",
        "incorrect_answers": ["David Tennant", "Peter Capaldi", "Tom Baker"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In the game &quot;Fire Emblem: Shadow Dragon&quot;, what is the central protagonist&#039;s name?",
        "correct_answer": "Marth",
        "incorrect_answers": ["Roy", "Eliwood", "Robin"],
    },
    {
        "type": "multiple",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "What does the F stand for in the FBI?",
        "correct_answer": "Federal",
        "incorrect_answers": ["Foreign", "Formal", "First"],
    },
]
